# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8fc09fdbe05faef1cd5cc10c37c75d17f553f420621be214ac24a6825ea985c561230825fb6e8c1d9e5cf8ca712408e91639badfad93aae45b891dd0366be4c

test:
  secret_key_base: 117ae7b2e1a1de0105a0c8d1beff1cb4e7b9d9b44e7ca5522a75f63198352a9888db09c334e339a0882f9816f2ed9b5a39e4152b0687b0b13361eead356f5081

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
